### ISSUE TITLE
进入某文章页面后 `Cannot access empty property in .../argon/functions.php:878`

### ISSUE THREAD

**Issue by potoo0** [solstice23/argon-theme#117]
版本:
Web Server | nginx/1.16.1
-- | --
PHP version | 7.0.33
Server API | fpm-fcgi
Server platform | Linux
Memory limit | 256M
Default PHP timezone | UTC
Disabled PHP functions |  
WordPress version | 5.4.2
WordPress locale | zh_CN
WordPress options DB table | wp_options
MySQLi | YES
MySQL Native Driver (mysqlnd) | YES
PHP allow_url_fopen | Enabled
PHP allow_url_include | Disabled

主页无错误，但进入某篇文章页面会报错误信息:
```
2020/11/30 20:09:56 [error] 1460#0: *25158 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Cannot access empty property in /var/www/html/wp-content/themes/argon/functions.php:878
Stack trace:
#0 /var/www/html/wp-content/themes/argon/functions.php(961): captcha_calculation->__construct(288960659)
#1 /var/www/html/wp-content/themes/argon/comments.php(138): get_comment_captcha_answer(288960659)
#2 /var/www/html/wp-includes/comment-template.php(1532): require('/var/www/html/w...')
#3 /var/www/html/wp-content/themes/argon/single.php(20): comments_template()
#4 /var/www/html/wp-includes/template-loader.php(106): include('/var/www/html/w...')
#5 /var/www/html/wp-blog-header.php(19): require_once('/var/www/html/w...')
#6 /var/www/html/index.php(17): require('/var/www/html/w...')
#7 {main}
  thrown in /var/www/html/wp-content/themes/argon/functions.php on line 878" while reading response header from upstream, client: 101.226.164.165, server: localhost
```

php session 文件夹用户组已经设置为 nginx，感觉不像是 sessionid 问题:
```
$ la
total 12K
drwxrwx--- 2 root nginx 4.0K Sep 29 16:37 opcache
drwxrwx--- 2 root nginx 4.0K Nov 30 20:12 session
drwxrwx--- 2 root nginx 4.0K Sep 29 16:37 wsdlcache
```
```
$ la session
total 16K
-rw------- 1 nginx nginx  0 Nov 30 19:57 sess_270e08r5rc09etepqlsb4c1os6
-rw------- 1 nginx nginx  0 Nov 30 19:56 sess_28730s391bojbhgl2imrtrlbo5
-rw------- 1 nginx nginx  0 Nov 30 19:52 sess_2q5tf1gqk5r861mogud2m22ai2
-rw------- 1 nginx nginx 23 Nov 30 20:09 sess_3bk2j3rj9l0tj1pte8g0jg4p05
```
```
$ grep -rin 288960659
sess_ugf65r00sakn83r56k4fod1qd1:1:captchaSeed|i:288960659;
```

有时间的话可以指点一下我吗？谢谢。

**Comment by AnRan-727** [comment]
我的也是这个问题   请问你的解决了吗

**Comment by potoo0** [comment]
> 我的也是这个问题 请问你的解决了吗

还没有，也不知道是不是 php 版本问题，主题不知道支持最新的 php 版本是多少。

**Comment by potoo0** [comment]
好的，release 期待中...
