### ISSUE TITLE
文章编辑页面js出错

### ISSUE THREAD

**Issue by ihkk** [solstice23/argon-theme#375]
启用Argon主题后，文章编辑页面的部分js无法正常运行。例如：文章可见性、发布时间的“编辑”点不了了；很多页面中的按钮（如下图框选的）也点不了。
之前的版本没有出现过类似的情况。更换其他主题后便恢复正常。
![](https://s2.loli.net/2022/01/26/Kx3UXWbR7TMNYgi.png)

以下为console报错内容。
```
mouse.min.js?ver=1.12.1:9 Uncaught TypeError: o.widget is not a function
    at mouse.min.js:9:166
    at mouse.min.js:9:82
    at mouse.min.js:9:92
sortable.min.js?ver=1.12.1:9 Uncaught TypeError: Cannot read properties of undefined (reading 'mouse')
    at sortable.min.js:9:150
    at sortable.min.js:9:92
    at sortable.min.js:9:102
menu.min.js?ver=1.12.1:9 Uncaught TypeError: a.widget is not a function
    at menu.min.js:9:114
    at menu.min.js:9:82
    at menu.min.js:9:92
autocomplete.min.js?ver=1.12.1:9 Uncaught TypeError: o.widget is not a function
    at autocomplete.min.js:9:123
    at autocomplete.min.js:9:91
    at autocomplete.min.js:9:101
draggable.min.js?ver=1.12.1:9 Uncaught TypeError: Cannot read properties of undefined (reading 'mouse')
    at draggable.min.js:9:151
    at draggable.min.js:9:92
    at draggable.min.js:9:102
slider.min.js?ver=1.12.1:9 Uncaught TypeError: Cannot read properties of undefined (reading 'mouse')
    at slider.min.js:9:148
    at slider.min.js:9:92
    at slider.min.js:9:102
iris.min.js?ver=1.0.7:5 Uncaught TypeError: a.widget is not a function
    at iris.min.js:5:16724
    at iris.min.js:5:16808
color-picker.min.js?ver=5.8.3:2 Uncaught TypeError: i.widget is not a function
    at color-picker.min.js:2:3418
    at color-picker.min.js:2:3447
load-scripts.php?c=0&load[chunk_0]=jquery-core,jquery-migrate,utils,jquery-ui-core,underscore,thickbox,shortcode,moxiejs,plupload,jquery-ui-tabs&ver=5.8.3:2 jQuery.Deferred exception: jQuery(...).datepicker is not a function TypeError: jQuery(...).datepicker is not a function
    at HTMLDocument.<anonymous> (https://ihkk.net/wp-content/plugins/wp-word-count/admin/js/wpwc-admin.js?ver=3.2.3:100:36)
    at e (https://ihkk.net/wp-admin/load-scripts.php?c=0&load%5Bchunk_0%5D=jquery-core,jquery-migrate,utils,jquery-ui-core,underscore,thickbox,shortcode,moxiejs,plupload,jquery-ui-tabs&ver=5.8.3:2:30038)
    at t (https://ihkk.net/wp-admin/load-scripts.php?c=0&load%5Bchunk_0%5D=jquery-core,jquery-migrate,utils,jquery-ui-core,underscore,thickbox,shortcode,moxiejs,plupload,jquery-ui-tabs&ver=5.8.3:2:30340) undefined
S.Deferred.exceptionHook @ load-scripts.php?c=0&load[chunk_0]=jquery-core,jquery-migrate,utils,jquery-ui-core,underscore,thickbox,shortcode,moxiejs,plupload,jquery-ui-tabs&ver=5.8.3:2
jquery.min.js:2 jQuery.Deferred exception: l(...).sortable is not a function TypeError: l(...).sortable is not a function
    at Object.init (https://ihkk.net/wp-admin/js/postbox.min.js?ver=5.8.3:2:3694)
    at Object.add_postbox_toggles (https://ihkk.net/wp-admin/js/postbox.min.js?ver=5.8.3:2:2733)
    at HTMLDocument.<anonymous> (https://ihkk.net/wp-admin/js/post.min.js?ver=5.8.3:2:4469)
    at j (https://ihkk.net/wp-content/themes/argon/assets/vendor/jquery/jquery.min.js:2:29999)
    at k (https://ihkk.net/wp-content/themes/argon/assets/vendor/jquery/jquery.min.js:2:30313) undefined
r.Deferred.exceptionHook @ jquery.min.js:2
load-scripts.php?c=0&load[chunk_0]=jquery-core,jquery-migrate,utils,jquery-ui-core,underscore,thickbox,shortcode,moxiejs,plupload,jquery-ui-tabs&ver=5.8.3:2 Uncaught TypeError: jQuery(...).datepicker is not a function
    at HTMLDocument.<anonymous> (wpwc-admin.js:100:36)
    at e (load-scripts.php:2:30038)
    at t (load-scripts.php:2:30340)
jquery.min.js:2 Uncaught TypeError: l(...).sortable is not a function
    at Object.init (postbox.min.js:2:3694)
    at Object.add_postbox_toggles (postbox.min.js:2:2733)
    at HTMLDocument.<anonymous> (post.min.js:2:4469)
    at j (jquery.min.js:2:29999)
    at k (jquery.min.js:2:30313)
```

**Comment by solstice23** [comment]
WordPress 5.9，argon master 分支，启用经典编辑器插件
无法复现，请检查是否有不兼容的插件

**Comment by ihkk** [comment]
仔细查看了console输出，停用插件**WP Word Count**之后恢复正常了
